import type { NextPage } from 'next';
import Head from 'next/head';
import { SpielFlaeche } from '../components/ui/SpielFlaeche';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tic Tac Toe App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className='text-center text-2xl mt-5'>Tic Tac Toe </h1>
      <main>
        <SpielFlaeche />
      </main>
    </div>
  );
};

export default Home;
